alter table product drop constraint FK_19w9vgbbv4qs6m0tkucs9ad0c
alter table product drop constraint FK_19w9vgbbv4qs6m0tkucs9ad0c
alter table purchase drop constraint FK_rf4yj0t3bq1f42596a7v71l1c
alter table purchase drop constraint FK_rf4yj0t3bq1f42596a7v71l1c
alter table purchaseitem drop constraint FK_5ta318a5vltt62onwwyv79rks
alter table purchaseitem drop constraint FK_5ta318a5vltt62onwwyv79rks
alter table purchaseitem drop constraint FK_1y3h3hbsrr3fbpuqbfj6ogoi2
alter table purchaseitem drop constraint FK_1y3h3hbsrr3fbpuqbfj6ogoi2



drop table category if exists
drop table customer if exists
drop table product if exists
drop table purchase if exists
drop table purchaseitem if exists
create table category (id bigint generated by default as identity (start with 1), description varchar(700) not null, name varchar(100) not null, version integer, primary key (id))
create table customer (id bigint generated by default as identity (start with 1), email varchar(255) not null, first_name varchar(255), last_name varchar(255), name varchar(100) not null, password varchar(255) not null, phone varchar(20), version integer, primary key (id))
create table product (id bigint generated by default as identity (start with 1), description varchar(700) not null, featured boolean, image_path varchar(700), price double not null, product_name varchar(100) not null, version integer, category bigint, primary key (id))
create table purchase (id bigint generated by default as identity (start with 1), completed boolean, order_date timestamp not null, version integer, ordered_by bigint, primary key (id))
create table purchaseitem (id bigint generated by default as identity (start with 1), order_date timestamp not null, quantity integer not null, version integer, product bigint, purchase bigint, primary key (id))
alter table product add constraint FK_19w9vgbbv4qs6m0tkucs9ad0c foreign key (category) references category
alter table purchase add constraint FK_rf4yj0t3bq1f42596a7v71l1c foreign key (ordered_by) references customer
alter table purchaseitem add constraint FK_5ta318a5vltt62onwwyv79rks foreign key (product) references product
alter table purchaseitem add constraint FK_1y3h3hbsrr3fbpuqbfj6ogoi2 foreign key (purchase) references purchase