// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.packtpub.springmvc.chocolatestore.model;

import com.packtpub.springmvc.chocolatestore.model.CustomerDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CustomerDataOnDemand_Roo_Configurable {
    
    declare @type: CustomerDataOnDemand: @Configurable;
    
}
