// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.packtpub.springmvc.chocolatestore.model;

import com.packtpub.springmvc.chocolatestore.model.ProductDataOnDemand;
import com.packtpub.springmvc.chocolatestore.model.PurchaseDataOnDemand;
import com.packtpub.springmvc.chocolatestore.model.PurchaseItem;
import com.packtpub.springmvc.chocolatestore.model.PurchaseItemDataOnDemand;
import com.packtpub.springmvc.chocolatestore.model.service.PurchaseItemService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PurchaseItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PurchaseItemDataOnDemand: @Component;
    
    private Random PurchaseItemDataOnDemand.rnd = new SecureRandom();
    
    private List<PurchaseItem> PurchaseItemDataOnDemand.data;
    
    @Autowired
    ProductDataOnDemand PurchaseItemDataOnDemand.productDataOnDemand;
    
    @Autowired
    PurchaseDataOnDemand PurchaseItemDataOnDemand.purchaseDataOnDemand;
    
    @Autowired
    PurchaseItemService PurchaseItemDataOnDemand.purchaseItemService;
    
    public PurchaseItem PurchaseItemDataOnDemand.getNewTransientPurchaseItem(int index) {
        PurchaseItem obj = new PurchaseItem();
        setOrderDate(obj, index);
        setQuantity(obj, index);
        return obj;
    }
    
    public void PurchaseItemDataOnDemand.setOrderDate(PurchaseItem obj, int index) {
        Calendar orderDate = Calendar.getInstance();
        obj.setOrderDate(orderDate);
    }
    
    public void PurchaseItemDataOnDemand.setQuantity(PurchaseItem obj, int index) {
        int quantity = index;
        obj.setQuantity(quantity);
    }
    
    public PurchaseItem PurchaseItemDataOnDemand.getSpecificPurchaseItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PurchaseItem obj = data.get(index);
        Long id = obj.getId();
        return purchaseItemService.findPurchaseItem(id);
    }
    
    public PurchaseItem PurchaseItemDataOnDemand.getRandomPurchaseItem() {
        init();
        PurchaseItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return purchaseItemService.findPurchaseItem(id);
    }
    
    public boolean PurchaseItemDataOnDemand.modifyPurchaseItem(PurchaseItem obj) {
        return false;
    }
    
    public void PurchaseItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = purchaseItemService.findPurchaseItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PurchaseItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PurchaseItem>();
        for (int i = 0; i < 10; i++) {
            PurchaseItem obj = getNewTransientPurchaseItem(i);
            try {
                purchaseItemService.savePurchaseItem(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
