// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.packtpub.springmvc.chocolatestore.model;

import com.packtpub.springmvc.chocolatestore.model.CustomerDataOnDemand;
import com.packtpub.springmvc.chocolatestore.model.Purchase;
import com.packtpub.springmvc.chocolatestore.model.PurchaseDataOnDemand;
import com.packtpub.springmvc.chocolatestore.model.service.PurchaseService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PurchaseDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PurchaseDataOnDemand: @Component;
    
    private Random PurchaseDataOnDemand.rnd = new SecureRandom();
    
    private List<Purchase> PurchaseDataOnDemand.data;
    
    @Autowired
    CustomerDataOnDemand PurchaseDataOnDemand.customerDataOnDemand;
    
    @Autowired
    PurchaseService PurchaseDataOnDemand.purchaseService;
    
    public Purchase PurchaseDataOnDemand.getNewTransientPurchase(int index) {
        Purchase obj = new Purchase();
        setCompleted(obj, index);
        setOrderDate(obj, index);
        return obj;
    }
    
    public void PurchaseDataOnDemand.setCompleted(Purchase obj, int index) {
        Boolean completed = Boolean.TRUE;
        obj.setCompleted(completed);
    }
    
    public void PurchaseDataOnDemand.setOrderDate(Purchase obj, int index) {
        Calendar orderDate = Calendar.getInstance();
        obj.setOrderDate(orderDate);
    }
    
    public Purchase PurchaseDataOnDemand.getSpecificPurchase(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Purchase obj = data.get(index);
        Long id = obj.getId();
        return purchaseService.findPurchase(id);
    }
    
    public Purchase PurchaseDataOnDemand.getRandomPurchase() {
        init();
        Purchase obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return purchaseService.findPurchase(id);
    }
    
    public boolean PurchaseDataOnDemand.modifyPurchase(Purchase obj) {
        return false;
    }
    
    public void PurchaseDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = purchaseService.findPurchaseEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Purchase' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Purchase>();
        for (int i = 0; i < 10; i++) {
            Purchase obj = getNewTransientPurchase(i);
            try {
                purchaseService.savePurchase(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
