// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.packtpub.springmvc.chocolatestore.model;

import com.packtpub.springmvc.chocolatestore.model.PurchaseItemDataOnDemand;
import com.packtpub.springmvc.chocolatestore.model.PurchaseItemIntegrationTest;
import com.packtpub.springmvc.chocolatestore.model.service.PurchaseItemService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PurchaseItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PurchaseItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PurchaseItemIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PurchaseItemIntegrationTest: @Transactional;
    
    @Autowired
    PurchaseItemDataOnDemand PurchaseItemIntegrationTest.dod;
    
    @Autowired
    PurchaseItemService PurchaseItemIntegrationTest.purchaseItemService;
    
    @Test
    public void PurchaseItemIntegrationTest.testCountAllPurchaseItems() {
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to initialize correctly", dod.getRandomPurchaseItem());
        long count = purchaseItemService.countAllPurchaseItems();
        Assert.assertTrue("Counter for 'PurchaseItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PurchaseItemIntegrationTest.testFindPurchaseItem() {
        PurchaseItem obj = dod.getRandomPurchaseItem();
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to provide an identifier", id);
        obj = purchaseItemService.findPurchaseItem(id);
        Assert.assertNotNull("Find method for 'PurchaseItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PurchaseItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PurchaseItemIntegrationTest.testFindAllPurchaseItems() {
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to initialize correctly", dod.getRandomPurchaseItem());
        long count = purchaseItemService.countAllPurchaseItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'PurchaseItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PurchaseItem> result = purchaseItemService.findAllPurchaseItems();
        Assert.assertNotNull("Find all method for 'PurchaseItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PurchaseItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PurchaseItemIntegrationTest.testFindPurchaseItemEntries() {
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to initialize correctly", dod.getRandomPurchaseItem());
        long count = purchaseItemService.countAllPurchaseItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PurchaseItem> result = purchaseItemService.findPurchaseItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PurchaseItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PurchaseItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PurchaseItemIntegrationTest.testFlush() {
        PurchaseItem obj = dod.getRandomPurchaseItem();
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to provide an identifier", id);
        obj = purchaseItemService.findPurchaseItem(id);
        Assert.assertNotNull("Find method for 'PurchaseItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPurchaseItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PurchaseItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PurchaseItemIntegrationTest.testUpdatePurchaseItemUpdate() {
        PurchaseItem obj = dod.getRandomPurchaseItem();
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to provide an identifier", id);
        obj = purchaseItemService.findPurchaseItem(id);
        boolean modified =  dod.modifyPurchaseItem(obj);
        Integer currentVersion = obj.getVersion();
        PurchaseItem merged = purchaseItemService.updatePurchaseItem(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PurchaseItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PurchaseItemIntegrationTest.testSavePurchaseItem() {
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to initialize correctly", dod.getRandomPurchaseItem());
        PurchaseItem obj = dod.getNewTransientPurchaseItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PurchaseItem' identifier to be null", obj.getId());
        try {
            purchaseItemService.savePurchaseItem(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PurchaseItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PurchaseItemIntegrationTest.testDeletePurchaseItem() {
        PurchaseItem obj = dod.getRandomPurchaseItem();
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PurchaseItem' failed to provide an identifier", id);
        obj = purchaseItemService.findPurchaseItem(id);
        purchaseItemService.deletePurchaseItem(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'PurchaseItem' with identifier '" + id + "'", purchaseItemService.findPurchaseItem(id));
    }
    
}
