// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.packtpub.springmvc.chocolatestore.model;

import com.packtpub.springmvc.chocolatestore.model.PurchaseDataOnDemand;
import com.packtpub.springmvc.chocolatestore.model.PurchaseIntegrationTest;
import com.packtpub.springmvc.chocolatestore.model.service.PurchaseService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PurchaseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PurchaseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PurchaseIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PurchaseIntegrationTest: @Transactional;
    
    @Autowired
    PurchaseDataOnDemand PurchaseIntegrationTest.dod;
    
    @Autowired
    PurchaseService PurchaseIntegrationTest.purchaseService;
    
    @Test
    public void PurchaseIntegrationTest.testCountAllPurchases() {
        Assert.assertNotNull("Data on demand for 'Purchase' failed to initialize correctly", dod.getRandomPurchase());
        long count = purchaseService.countAllPurchases();
        Assert.assertTrue("Counter for 'Purchase' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PurchaseIntegrationTest.testFindPurchase() {
        Purchase obj = dod.getRandomPurchase();
        Assert.assertNotNull("Data on demand for 'Purchase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Purchase' failed to provide an identifier", id);
        obj = purchaseService.findPurchase(id);
        Assert.assertNotNull("Find method for 'Purchase' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Purchase' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PurchaseIntegrationTest.testFindAllPurchases() {
        Assert.assertNotNull("Data on demand for 'Purchase' failed to initialize correctly", dod.getRandomPurchase());
        long count = purchaseService.countAllPurchases();
        Assert.assertTrue("Too expensive to perform a find all test for 'Purchase', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Purchase> result = purchaseService.findAllPurchases();
        Assert.assertNotNull("Find all method for 'Purchase' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Purchase' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PurchaseIntegrationTest.testFindPurchaseEntries() {
        Assert.assertNotNull("Data on demand for 'Purchase' failed to initialize correctly", dod.getRandomPurchase());
        long count = purchaseService.countAllPurchases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Purchase> result = purchaseService.findPurchaseEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Purchase' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Purchase' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PurchaseIntegrationTest.testFlush() {
        Purchase obj = dod.getRandomPurchase();
        Assert.assertNotNull("Data on demand for 'Purchase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Purchase' failed to provide an identifier", id);
        obj = purchaseService.findPurchase(id);
        Assert.assertNotNull("Find method for 'Purchase' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPurchase(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Purchase' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PurchaseIntegrationTest.testUpdatePurchaseUpdate() {
        Purchase obj = dod.getRandomPurchase();
        Assert.assertNotNull("Data on demand for 'Purchase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Purchase' failed to provide an identifier", id);
        obj = purchaseService.findPurchase(id);
        boolean modified =  dod.modifyPurchase(obj);
        Integer currentVersion = obj.getVersion();
        Purchase merged = purchaseService.updatePurchase(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Purchase' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PurchaseIntegrationTest.testSavePurchase() {
        Assert.assertNotNull("Data on demand for 'Purchase' failed to initialize correctly", dod.getRandomPurchase());
        Purchase obj = dod.getNewTransientPurchase(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Purchase' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Purchase' identifier to be null", obj.getId());
        try {
            purchaseService.savePurchase(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Purchase' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PurchaseIntegrationTest.testDeletePurchase() {
        Purchase obj = dod.getRandomPurchase();
        Assert.assertNotNull("Data on demand for 'Purchase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Purchase' failed to provide an identifier", id);
        obj = purchaseService.findPurchase(id);
        purchaseService.deletePurchase(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Purchase' with identifier '" + id + "'", purchaseService.findPurchase(id));
    }
    
}
